[package]
name = "salvo"
version = "0.1.0"
authors = ["Browning Keith Smith <browningsmith@email.arizona.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

console = "0.9.1"
